Repository humanmade/altis-security, pull requests merged in 2022-02, with the labels that each got.

#155 Fix universally forced 2fa logic
  inc/namespace.php
Labels: backport v7-branch, backport v8-branch, backport v9-branch

#163 Add HSTS header support
  composer.json
  docs/browser.md
  load.php
Labels: backport v10-branch

#166 Force the use of basic auth on prod
  inc/php_basic_auth/namespace.php
Labels: backport v8-branch, backport v9-branch, backport v10-branch
